# kubectl apply -f k8s.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: smart
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: smart-ingress
  namespace: smart
spec:
  rules:
  - host: smart.argo.run
    http:
      paths:
      - backend:
          serviceName: smart
          servicePort: 80
        path: /(.*)
  tls:
  - hosts:
    - smart.argo.run
    secretName: tls-secret
status:
  loadBalancer:
    ingress:
    - {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: smart
  name: smart
spec:
  selector:
    app: smart
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart
  namespace: smart
  labels:
    app: smart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart
  template:
    metadata:
      labels:
        app: smart
    spec:
      volumes:
      containers:
      - name: ui
        image: argonautcontainerregistry.azurecr.io/smart:latest
        ports:
        - containerPort: 9009
        env:
        - name: SERVER_BASE
          value: "https://smart.argo.run/"
